name: PR Validation

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master
      - main

jobs:
  validate-files:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Get changed files
        id: changed-files
        run: |
          # Get the list of changed files in the PR
          git fetch origin ${{ github.base_ref }}
          CHANGED_FILES=$(git diff --name-only origin/${{ github.base_ref }}...HEAD)
          echo "Changed files:"
          echo "$CHANGED_FILES"
          echo "changed_files<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGED_FILES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      
      - name: Validate PR requirements
        run: python .github/scripts/validate_pr.py
        env:
          CHANGED_FILES: ${{ steps.changed-files.outputs.changed_files }}
      
      - name: Run pylint on all Python files
        if: false
        run: |
          git ls-files '*.py' | uv run xargs pylint

      - name: Run pylint on changed Python files
        if: ${{ steps.changed-files.outputs.changed_files }}
        run: |
          echo "${{ steps.changed-files.outputs.changed_files }}" | grep '\.py$' | uv run xargs pylint

